// Code generated by github.com/Just4Ease/graphrpc, DO NOT EDIT.

package vendorService

import (
	axon "github.com/Just4Ease/axon/v2"
	"github.com/Just4Ease/graphrpc"
	"github.com/Just4Ease/graphrpc/client"
)

type ServiceClient struct {
	client *client.Client
}

func NewClient(conn axon.EventStore, options ...graphrpc.ClientOption) (*ServiceClient, error) {
	client, err := graphrpc.NewClient(conn, options...)
	if err != nil {
		return nil, err
	}

	return &ServiceClient{client: client}, nil
}

type Query struct {
	ListVendors   *VendorList "json:\"listVendors\" graphql:\"listVendors\""
	GetVendorByID *Vendor     "json:\"getVendorById\" graphql:\"getVendorById\""
}
type Mutation struct {
	CreateVendor     *Result "json:\"createVendor\" graphql:\"createVendor\""
	UpdateVendor     *Result "json:\"updateVendor\" graphql:\"updateVendor\""
	ActivateVendor   *Result "json:\"activateVendor\" graphql:\"activateVendor\""
	DeactivateVendor *Result "json:\"deactivateVendor\" graphql:\"deactivateVendor\""
}
